AllCops:
  Exclude:
    - 'bin/**/*'
    - 'assets/**/*'
  DisplayCopNames: true
  TargetRubyVersion: 2.3
  SuggestExtensions: false
  NewCops: enable

Style/ClassAndModuleChildren:
  Enabled: false
Layout/EndOfLine:
  EnforcedStyle: lf
Metrics/BlockLength:
  Max: 50
Layout/EmptyLineAfterGuardClause:
  Enabled: false
Metrics/AbcSize:
  Max: 50
Metrics/CyclomaticComplexity:
  Max: 12
Metrics/ClassLength:
  Max: 120
Metrics/MethodLength:
  Max: 100
Metrics/PerceivedComplexity:
  Max: 12
Metrics/ParameterLists:
  Max: 6
