# SPDX-FileCopyrightText: Copyright (c) 2019-2025 Yegor Bugayenko
# SPDX-License-Identifier: MIT
---
AllCops:
  Exclude:
    - 'bin/**/**'
    - 'assets/**/**'
    - 'vendor/**/**'
  DisplayCopNames: true
  TargetRubyVersion: 2.3
  SuggestExtensions: false
  NewCops: enable
Minitest/EmptyLineBeforeAssertionMethods:
  Enabled: false
Style/ClassAndModuleChildren:
  Enabled: false
Layout/EndOfLine:
  EnforcedStyle: lf
Metrics/BlockLength:
  Max: 100
Layout/EmptyLineAfterGuardClause:
  Enabled: false
Metrics/AbcSize:
  Max: 100
Metrics/CyclomaticComplexity:
  Max: 15
Metrics/ClassLength:
  Max: 200
Metrics/MethodLength:
  Max: 100
Metrics/PerceivedComplexity:
  Max: 15
Metrics/ParameterLists:
  Max: 6
plugins:
  - rubocop-rake
  - rubocop-minitest
  - rubocop-performance
