AllCops:
  Exclude:
    - 'bin/**/*'
    - 'assets/**/*'
  DisplayCopNames: true
  TargetRubyVersion: 2.3

Style/ClassAndModuleChildren:
  Enabled: false
Layout/EndOfLine:
  EnforcedStyle: lf
Metrics/BlockLength:
  Max: 50
Layout/EmptyLineAfterGuardClause:
  Enabled: false
Metrics/AbcSize:
  Max: 50
Metrics/CyclomaticComplexity:
  Max: 10
Metrics/MethodLength:
  Max: 100
Metrics/PerceivedComplexity:
  Max: 10
