assets:
  rubygems.yml: yegor256/home#assets/rubygems.yml
  s3cfg: yegor256/home#assets/s3cfg
install: |
  export PATH=$PATH:/usr/lib/postgresql/10/bin
  sudo apt-get -y update
  sudo apt-get -y install libpq-dev
  export GEM_HOME=~/.ruby
  export GEM_PATH=$GEM_HOME:$GEM_PATH
  sudo apt-get -y update
  sudo gem install pdd
release:
  script: |-
    bundle install
    rake
    rm -rf *.gem
    sed -i "s/1\.0\.snapshot/${tag}/g" lib/pgtk/version.rb
    git add lib/pgtk/version.rb
    git commit -m "version set to ${tag}"
    gem build pgtk.gemspec
    chmod 0600 ../rubygems.yml
    gem push *.gem --config-file ../rubygems.yml
  commanders:
  - yegor256
architect:
- yegor256
merge:
  script: |-
    bundle install
    bundle exec rake
    pdd -f /dev/null
deploy:
  script: |-
    echo "There is nothing to deploy"
    exit -1
