# SPDX-FileCopyrightText: Copyright (c) 2019-2026 Yegor Bugayenko
# SPDX-License-Identifier: MIT
---
# yamllint disable rule:line-length
docker:
  image: yegor256/java
assets:
  rubygems.yml: yegor256/home#assets/rubygems.yml
install: |
  sudo apt-get update --yes --fix-missing
  sudo apt-get install --yes libpq-dev postgresql-client postgresql
  sudo ln -s "$(realpath /usr/lib/postgresql/*/bin/initdb)" /bin/initdb
  sudo ln -s "$(realpath /usr/lib/postgresql/*/bin/postgres)" /bin/postgres
  sudo ln -s "$(realpath /usr/lib/postgresql/*/bin/pg_ctl)" /bin/pg_ctl
  pdd -f /dev/null
  bundle install --no-color
release:
  pre: false
  script: |-
    [[ "${tag}" =~ ^[0-9]+\.[0-9]+\.[0-9]+$ ]] || exit -1
    bundle exec rake
    rm -rf *.gem
    sed -i "s/0\.0\.0/${tag}/g" lib/pgtk/version.rb
    git add lib/pgtk/version.rb
    git commit -m "version set to ${tag}"
    gem build pgtk.gemspec
    chmod 0600 ../rubygems.yml
    gem push *.gem --config-file ../rubygems.yml
merge:
  script: |-
    bundle exec rake
