# SPDX-FileCopyrightText: Copyright (c) 2019-2025 Yegor Bugayenko
# SPDX-License-Identifier: MIT
---
# yamllint disable rule:line-length
name: codecov
'on':
  push:
    branches:
      - master
jobs:
  codecov:
    timeout-minutes: 15
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.3
          bundler-cache: true
      - run: |
          sudo apt-get update --yes --fix-missing
          sudo apt-get install --yes libpq-dev postgresql-client postgresql
          sudo ln -s "$(realpath /usr/lib/postgresql/*/bin/initdb)" /bin/initdb
          sudo ln -s "$(realpath /usr/lib/postgresql/*/bin/postgres)" /bin/postgres
          sudo ln -s "$(realpath /usr/lib/postgresql/*/bin/pg_ctl)" /bin/pg_ctl
      - run: bundle config set --global path "$(pwd)/vendor/bundle"
      - run: bundle install --no-color
      - run: bundle exec rake
      - uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
